extensions:
  client:
    endpoints:
      - ${UPSTREAM_URL}
  event_bus:
  eth_api:
    stale_timeout_seconds: 90 # rotate endpoint if no new blocks for 1.5 minutes
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 30
    default_size: 0
  server:
    port: ${RPC_PORT}
    listen_address: "0.0.0.0"
    max_connections: 10000
    max_batch_size: 10
    cors: all
  prometheus:
    port: ${METRICS_PORT}
    listen_address: "0.0.0.0"
    label: "dev"

middlewares:
  methods:
    - cache
    - upstream
  subscriptions:
    - upstream

rpcs: ethereum
