extensions:
  client:
    endpoints:
      - wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v1
  event_bus:
  eth_api:
    stale_timeout_seconds: 180 # rotate endpoint if no new blocks for 3 minutes
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 30
    default_size: 0
  server:
    port: 8545
    listen_address: "0.0.0.0"
    max_connections: 2000
    max_batch_size: 10
    cors: all
  prometheus:
    port: 9616
    listen_address: "0.0.0.0"
    label: "dev"

middlewares:
  methods:
    - cache
    - upstream
  subscriptions:
    - upstream

rpcs: ethereum
